spring:
  datasource:
    url: jdbc:mysql://localhost:3306/your_db
    username: your_username
    password: your_password

server:
  port: 8080

mqtt:
  broker: tcp://broker.hivemq.com:1883
  topic: sensor/data
